# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "app".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
version: '3.2'

services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/logs:/var/log/nginx
    ports:
      - 80:80
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker/php
      dockerfile: Dockerfile
    user: root
    volumes:
      - ./:/var/www/html
      - ./storage/public/storage/:/var/www/html/public/storage
    working_dir: /var/www/html
  
  mysql:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 33060:3306
    environment:
      - MYSQL_DATABASE=ecommerce
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root

volumes:
  mysql-volume: